In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
trans = pd.read_csv('/content/train_transaction.csv')
ident = pd.read_csv('/content/train_identity.csv')

In [4]:
# merging both dataset

df = pd.merge(trans,ident,on='TransactionID' , how='left')

In [5]:
df

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,3060943,0,1633205,40.0,W,9500,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73944,3060944,0,1633214,49.0,W,12695,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73945,3060945,0,1633223,35.0,W,1342,514.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73946,3060946,0,1633229,100.0,S,6019,583.0,150.0,visa,226.0,...,firefox 57.0,24.0,1680x1050,match_status:2,T,F,T,T,desktop,Windows
73947,3060947,0,1633235,30.0,H,14128,170.0,150.0,mastercard,219.0,...,chrome 63.0,24.0,1920x1080,match_status:2,T,F,T,T,desktop,Windows

In [30]:
## step 1 - Missing ValueS Handling
## Drop columns which have more than 70 % missing Values
missing = df.isnull().mean() * 100

drop_cols = missing[missing >=70].index

df.drop(columns=drop_cols, inplace=True)

df.shape

(73948, 355)

In [35]:
## missing value Distribution

missing.describe()

count    355.000000
mean      36.243839
std       28.267237
min        0.000000
25%        0.016228
50%       32.787905
75%       64.856386
max       69.839617
dtype: float64

In [32]:
missing[missing>70]

Series([], dtype: float64)

In [33]:
df

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,3060943,0,1633205,40.0,W,9500,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73944,3060944,0,1633214,49.0,W,12695,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73945,3060945,0,1633223,35.0,W,1342,514.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73946,3060946,0,1633229,100.0,S,6019,583.0,150.0,visa,226.0,...,368.0,New,NotFound,firefox 57.0,T,F,T,T,desktop,Windows
73947,3060947,0,1633235,30.0,H,14128,170.0,150.0,mastercard,219.0,...,533.0,Found,Found,chrome 63.0,T,F,T,T,desktop,Windows

In [34]:
drop_cols = missing[missing > 80].index
len(drop_cols)

0

## Removing Features with High Missing Values

Columns with 70% or more missing values were removed from the dataset.
Such features contain very little usable information and may introduce noise into the model.

Dropping these columns helps simplify the dataset and improves model efficiency.

In [36]:
## 2 . Remove Identifier and Non - predictive Features

df.drop(columns=['TransactionID'], inplace=True, errors='ignore')

In [44]:
df.nunique().sort_values().head(30)

V305          2
M5            2
M3            2
V1            2
M6            2
M2            2
V14           2
V41           2
isFraud       2
id_28         2
id_16         2
id_12         2
V94           2
V88           2
V65           2
id_29         2
id_37         2
id_36         2
DeviceType    2
id_38         2
id_35         2
id_15         3
V27           3
V89           3
V241          3
V28           3
V119          3
V120          3
V118          3
V117          3
dtype: int64

In [39]:
low_var_cols = df.nunique()[df.nunique() <= 1].index

df.drop(columns=low_var_cols, inplace=True)

In [40]:
df.shape

(73948, 352)

Removing Unpredictive and Highly Correlated Features

In this step, we remove features that do not contribute useful information to the model and may negatively affect performance.

 *Removing* Unpredictive Features

Some columns such as unique identifiers or columns with only one unique value do not help the model learn patterns. These features are removed because they do not provide predictive power.

Examples include:

TransactionID (unique identifier)

Columns with only one unique value

Removing these features helps reduce noise and improves model efficiency.

In [49]:
###  3 . Correlated features handle
df.select_dtypes(include='number').corr().head(20)

,isFraud,TransactionDT,TransactionAmt,card1,card2,card3,card5,addr1,addr2,dist1,...,V320,V321,id_01,id_02,id_05,id_06,id_11,id_17,id_19,id_20
isFraud,1.000000,-0.005364,0.007155,-0.019335,-0.008524,0.154374,-0.038884,-0.011755,-0.086870,0.011910,...,0.011641,0.001749,-0.110807,0.057112,-0.018456,-0.041700,0.010883,0.196776,-0.059581,0.038055
TransactionDT,-0.005364,1.000000,-0.007853,0.003397,0.043497,0.023756,-0.004377,-0.009062,0.025944,0.002455,...,-0.004081,-0.001404,-0.007480,-0.010374,0.013996,-0.005108,0.019197,-0.061230,-0.007937,-0.024968
TransactionAmt,0.007155,-0.007853,1.000000,-0.010952,0.005964,-0.107231,-0.011205,-0.011883,0.069917,0.036084,...,0.076211,0.070657,-0.019357,0.054359,0.017413,0.020946,-0.022777,-0.225160,0.056233,-0.064249
card1,-0.019335,0.003397,-0.010952,1.000000,-0.009706,-0.002697,-0.078312,0.020174,-0.003184,0.004499,...,0.007033,0.003306,-0.000740,0.004799,0.002155,-0.001099,0.004203,0.014316,0.010044,0.006184
card2,-0.008524,0.043497,0.005964,-0.009706,1.000000,0.014901,0.033957,0.023910,-0.035984,-0.015075,...,0.000648,-0.000932,-0.000197,-0.019660,-0.005608,0.000677,-0.016803,-0.032473,-0.000527,-0.004708
card3,0.154374,0.023756,-0.107231,-0.002697,0.014901,1.000000,-0.157367,0.032890,-0.660179,-0.004572,...,-0.012698,-0.008506,-0.075255,0.295881,-0.108936,-0.060204,0.046424,0.807199,-0.151977,0.233316
card5,-0.038884,-0.004377,-0.011205,-0.078312,0.033957,-0.157367,1.000000,0.028100,0.085596,0.003439,...,0.005082,0.000870,0.023426,-0.099379,0.023256,0.015229,-0.018629,-0.178637,0.038347,-0.079095
addr1,-0.011755,-0.009062,-0.011883,0.020174,0.023910,0.032890,0.028100,1.000000,-0.024845,-0.002861,...,-0.006853,-0.001470,0.008722,0.001916,-0.011624,0.002839,0.011123,0.030473,0.012623,-0.064289
addr2,-0.086870,0.025944,0.069917,-0.003184,-0.035984,-0.660179,0.085596,-0.024845,1.000000,NaN,...,0.000859,0.004521,0.080341,-0.252277,0.084538,0.016007,0.003139,-0.751251,0.099003,-0.121409
dist1,0.011910,0.002455,0.036084,0.004499,-0.015075,-0.004572,0.003439,-0.002861,NaN,1.000000,...,0.011319,0.014086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C1,0.066852,0.075269,-0.044227,0.014212,0.018947,0.278344,-0.061618,-0.002219,-0.060267,-0.036554,...,0.001392,-0.003564,-0.056094,0.089045,-0.030754,-0.040872,0.007489,0.279077,-0.076991,0.058528
C2,0.071039,0.074809,-0.046170,0.014434,0.019841,0.292106,-0.064401,-0.001641,-0.079224,-0.034677,...,0.001642,-0.003600,-0.061143,0.094638,-0.031521,-0.045183,0.010847,0.294692,-0.078755,0.064643
C3,-0.016597,-0.005102,-0.025113,-0.005443,0.011037,-0.028296,0.000496,0.006458,0.018691,NaN,...,0.031864,0.034815,0.034089,-0.108620,-0.002740,0.018992,-0.010265,-0.081679,0.010838,0.035465
C4,0.068218,0.079641,-0.041831,0.013876,0.022142,0.285639,-0.065359,-0.002379,-0.068694,NaN,...,0.002213,-0.003152,-0.062581,0.093180,-0.030740,-0.043641,0.000552,0.281753,-0.080538,0.056527
C5,-0.028058,-0.029742,-0.027958,0.010527,-0.029208,-0.055096,0.025788,0.000688,0.036621,-0.033320,...,-0.005117,-0.004652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C6,0.065156,0.076538,-0.044522,0.015357,0.018793,0.278119,-0.061893,-0.002385,-0.045043,-0.036356,...,0.001729,-0.003615,-0.062687,0.093091,-0.030686,-0.043561,0.000049,0.281163,-0.080618,0.056036
C7,0.069312,0.073017,-0.046905,0.013611,0.020308,0.294045,-0.065893,0.000039,-0.134542,NaN,...,0.001761,-0.003657,-0.051136,0.093456,-0.030757,-0.043357,0.027205,0.297915,-0.070775,0.074520
C8,0.068751,0.076266,-0.044847,0.013414,0.021237,0.289383,-0.065370,-0.000553,-0.106588,NaN,...,0.001993,-0.003426,-0.055065,0.092322,-0.030649,-0.043395,0.015925,0.289747,-0.074665,0.066445
C9,-0.026918,-0.031980,-0.027912,0.011771,-0.033839,-0.066170,0.031911,-0.000946,0.044384,-0.033878,...,-0.003862,-0.004391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C10,0.070368,0.075267,-0.046786,0.013843,0.021211,0.297111,-0.066905,-0.000656,-0.113887,NaN,...,0.002142,-0.003572,-0.058031,0.096193,-0.030917,-0.046996,0.019479,0.300143,-0.075316,0.071334

In [50]:
corr = df.select_dtypes(include='number').corr().abs()

for col in corr.columns:
    for row in corr.index:
        if col != row and corr.loc[row,col] > 0.7:
            print(row, col)

V50 card3
V51 card3
V52 card3
V57 card3
V58 card3
V73 card3
V74 card3
V79 card3
V94 card3
id_17 card3
V15 addr2
V33 addr2
V34 addr2
V50 addr2
V51 addr2
V52 addr2
V57 addr2
V58 addr2
V71 addr2
V72 addr2
V73 addr2
V74 addr2
V79 addr2
V94 addr2
id_17 addr2
C2 C1
C4 C1
C6 C1
C7 C1
C8 C1
C10 C1
C11 C1
C12 C1
C13 C1
C14 C1
C1 C2
C4 C2
C6 C2
C7 C2
C8 C2
C10 C2
C11 C2
C12 C2
C13 C2
C14 C2
V27 C3
V28 C3
C1 C4
C2 C4
C6 C4
C7 C4
C8 C4
C10 C4
C11 C4
C12 C4
C13 C4
C14 C4
C9 C5
C1 C6
C2 C6
C4 C6
C7 C6
C8 C6
C10 C6
C11 C6
C12 C6
C13 C6
C14 C6
C1 C7
C2 C7
C4 C7
C6 C7
C8 C7
C10 C7
C11 C7
C12 C7
C13 C7
C14 C7
C1 C8
C2 C8
C4 C8
C6 C8
C7 C8
C10 C8
C11 C8
C12 C8
C13 C8
C14 C8
C5 C9
C1 C10
C2 C10
C4 C10
C6 C10
C7 C10
C8 C10
C11 C10
C12 C10
C13 C10
C14 C10
C1 C11
C2 C11
C4 C11
C6 C11
C7 C11
C8 C11
C10 C11
C12 C11
C13 C11
C14 C11
C1 C12
C2 C12
C4 C12
C6 C12
C7 C12
C8 C12
C10 C12
C11 C12
C13 C12
C14 C12
C1 C13
C2 C13
C4 C13
C6 C13
C7 C13
C8 C13
C10 C13
C11 C13
C12 C13
C14 C13
C1 C14
C2 C14
C4 C14
C6 C14
C7 C14
C8 C14
C10 C14
C11 C14
C12 C14
C13 C14
D2 D1
D1 D2
D5 D3
D15 D4
D3 D5
D15 D10
D15 D11
D4 D15
D10 D15
D11 D15
V3 V2
V2 V3
V5 V4
V82 V4
V4 V5
V7 V6
V6 V7
V9 V8
V8 V9
V11 V10
V29 V10
V30 V10
V48 V10
V49 V10
V69 V10
V70 V10
V90 V10
V91 V10
V10 V11
V29 V11
V30 V11
V48 V11
V49 V11
V69 V11
V70 V11
V90 V11
V91 V11
V13 V12
V75 V12
V12 V13
V76 V13
V41 V14
V65 V14
V88 V14
addr2 V15
V16 V15
V18 V15
V21 V15
V22 V15
V31 V15
V32 V15
V33 V15
V34 V15
V42 V15
V50 V15
V51 V15
V52 V15
V57 V15
V58 V15
V59 V15
V60 V15
V63 V15
V64 V15
V71 V15
V72 V15
V73 V15
V74 V15
V79 V15
V84 V15
V92 V15
V93 V15
V94 V15
V15 V16
V18 V16
V22 V16
V31 V16
V32 V16
V33 V16
V34 V16
V50 V16
V51 V16
V52 V16
V57 V16
V58 V16
V71 V16
V72 V16
V73 V16
V74 V16
V79 V16
V92 V16
V93 V16
V94 V16
V18 V17
V21 V17
V22 V17
V31 V17
V32 V17
V33 V17
V39 V17
V40 V17
V42 V17
V43 V17
V50 V17
V57 V17
V58 V17
V59 V17
V60 V17
V63 V17
V64 V17
V71 V17
V72 V17
V73 V17
V80 V17
V81 V17
V84 V17
V85 V17
V92 V17
V93 V17
V94 V17
V302 V17
V303 V17
V304 V17
V15 V18
V16 V18
V17 V18
V21 V18
V22 V18
V31 V18
V32 V18
V33 V18
V34 V18
V39 V18
V40 V18
V42 V18
V43 V18
V50 V18
V59 V18
V60 V18
V63 V18
V64 V18
V71 V18
V72 V18
V80 V18
V81 V18
V84 V18
V85 V18
V92 V18
V93 V18
V302 V18
V303 V18
V304 V18
V20 V19
V61 V19
V82 V19
V19 V20
V15 V21
V17 V21
V18 V21
V22 V21
V31 V21
V32 V21
V33 V21
V39 V21
V40 V21
V42 V21
V43 V21
V50 V21
V51 V21
V52 V21
V57 V21
V58 V21
V59 V21
V60 V21
V63 V21
V64 V21
V71 V21
V72 V21
V73 V21
V74 V21
V79 V21
V80 V21
V81 V21
V84 V21
V85 V21
V92 V21
V93 V21
V94 V21
V302 V21
V303 V21
V304 V21
V15 V22
V16 V22
V17 V22
V18 V22
V21 V22
V31 V22
V32 V22
V33 V22
V34 V22
V39 V22
V40 V22
V42 V22
V43 V22
V50 V22
V51 V22
V57 V22
V58 V22
V59 V22
V60 V22
V63 V22
V64 V22
V71 V22
V72 V22
V73 V22
V74 V22
V79 V22
V80 V22
V81 V22
V84 V22
V85 V22
V92 V22
V93 V22
V94 V22
V302 V22
V303 V22
V304 V22
V24 V23
V23 V24
V26 V25
V25 V26
C3 V27
V28 V27
V68 V27
V89 V27
C3 V28
V27 V28
V68 V28
V89 V28
V10 V29
V11 V29
V30 V29
V48 V29
V49 V29
V69 V29
V70 V29
V90 V29
V91 V29
V10 V30
V11 V30
V29 V30
V48 V30
V49 V30
V69 V30
V70 V30
V90 V30
V91 V30
V15 V31
V16 V31
V17 V31
V18 V31
V21 V31
V22 V31
V32 V31
V33 V31
V34 V31
V39 V31
V40 V31
V42 V31
V43 V31
V50 V31
V51 V31
V52 V31
V57 V31
V58 V31
V59 V31
V60 V31
V63 V31
V64 V31
V71 V31
V72 V31
V73 V31
V74 V31
V79 V31
V80 V31
V81 V31
V84 V31
V85 V31
V92 V31
V93 V31
V94 V31
V302 V31
V304 V31
V15 V32
V16 V32
V17 V32
V18 V32
V21 V32
V22 V32
V31 V32
V33 V32
V34 V32
V50 V32
V51 V32
V52 V32
V57 V32
V58 V32
V71 V32
V72 V32
V73 V32
V74 V32
V79 V32
V84 V32
V92 V32
V93 V32
V94 V32
addr2 V33
V15 V33
V16 V33
V17 V33
V18 V33
V21 V33
V22 V33
V31 V33
V32 V33
V34 V33
V39 V33
V42 V33
V43 V33
V50 V33
V51 V33
V52 V33
V57 V33
V58 V33
V59 V33
V60 V33
V63 V33
V64 V33
V71 V33
V72 V33
V73 V33
V74 V33
V79 V33
V84 V33
V85 V33
V92 V33
V93 V33
V94 V33
addr2 V34
V15 V34
V16 V34
V18 V34
V22 V34
V31 V34
V32 V34
V33 V34
V50 V34
V51 V34
V52 V34
V57 V34
V58 V34
V71 V34
V72 V34
V73 V34
V74 V34
V79 V34
V92 V34
V93 V34
V94 V34
V36 V35
V75 V35
V76 V35
V35 V36
V75 V36
V76 V36
V38 V37
V37 V38
V78 V38
V17 V39
V18 V39
V21 V39
V22 V39
V31 V39
V33 V39
V40 V39
V42 V39
V43 V39
V50 V39
V51 V39
V52 V39
V57 V39
V58 V39
V59 V39
V60 V39
V63 V39
V64 V39
V71 V39
V72 V39
V73 V39
V74 V39
V79 V39
V80 V39
V81 V39
V84 V39
V85 V39
V92 V39
V93 V39
V94 V39
V302 V39
V303 V39
V304 V39
V17 V40
V18 V40
V21 V40
V22 V40
V31 V40
V39 V40
V42 V40
V43 V40
V50 V40
V51 V40
V52 V40
V57 V40
V58 V40
V59 V40
V60 V40
V63 V40
V64 V40
V71 V40
V72 V40
V73 V40
V74 V40
V79 V40
V80 V40
V81 V40
V84 V40
V85 V40
V92 V40
V93 V40
V94 V40
V302 V40
V303 V40
V304 V40
V14 V41
V65 V41
V88 V41
V15 V42
V17 V42
V18 V42
V21 V42
V22 V42
V31 V42
V33 V42
V39 V42
V40 V42
V43 V42
V50 V42
V51 V42
V52 V42
V57 V42
V58 V42
V59 V42
V60 V42
V63 V42
V64 V42
V71 V42
V72 V42
V73 V42
V74 V42
V79 V42
V80 V42
V81 V42
V84 V42
V85 V42
V92 V42
V93 V42
V94 V42
V302 V42
V303 V42
V304 V42
V17 V43
V18 V43
V21 V43
V22 V43
V31 V43
V33 V43
V39 V43
V40 V43
V42 V43
V50 V43
V51 V43
V52 V43
V57 V43
V58 V43
V59 V43
V60 V43
V63 V43
V64 V43
V71 V43
V72 V43
V73 V43
V74 V43
V79 V43
V80 V43
V81 V43
V84 V43
V85 V43
V92 V43
V93 V43
V94 V43
V302 V43
V303 V43
V304 V43
V45 V44
V44 V45
V87 V45
V257 V45
V47 V46
V46 V47
V10 V48
V11 V48
V29 V48
V30 V48
V49 V48
V69 V48
V70 V48
V90 V48
V91 V48
V10 V49
V11 V49
V29 V49
V30 V49
V48 V49
V69 V49
V70 V49
V90 V49
V91 V49
card3 V50
addr2 V50
V15 V50
V16 V50
V17 V50
V18 V50
V21 V50
V22 V50
V31 V50
V32 V50
V33 V50
V34 V50
V39 V50
V40 V50
V42 V50
V43 V50
V51 V50
V52 V50
V57 V50
V58 V50
V59 V50
V60 V50
V63 V50
V64 V50
V71 V50
V72 V50
V73 V50
V74 V50
V79 V50
V80 V50
V81 V50
V84 V50
V85 V50
V92 V50
V93 V50
V94 V50
V302 V50
V303 V50
V304 V50
card3 V51
addr2 V51
V15 V51
V16 V51
V21 V51
V22 V51
V31 V51
V32 V51
V33 V51
V34 V51
V39 V51
V40 V51
V42 V51
V43 V51
V50 V51
V52 V51
V57 V51
V58 V51
V59 V51
V60 V51
V63 V51
V64 V51
V71 V51
V72 V51
V73 V51
V74 V51
V79 V51
V80 V51
V81 V51
V84 V51
V85 V51
V92 V51
V93 V51
V94 V51
V302 V51
V304 V51
card3 V52
addr2 V52
V15 V52
V16 V52
V21 V52
V31 V52
V32 V52
V33 V52
V34 V52
V39 V52
V40 V52
V42 V52
V43 V52
V50 V52
V51 V52
V57 V52
V58 V52
V59 V52
V60 V52
V63 V52
V64 V52
V71 V52
V72 V52
V73 V52
V74 V52
V79 V52
V80 V52
V84 V52
V85 V52
V92 V52
V93 V52
V94 V52
V302 V52
V304 V52
V54 V53
V53 V54
V56 V55
V55 V56
card3 V57
addr2 V57
V15 V57
V16 V57
V17 V57
V21 V57
V22 V57
V31 V57
V32 V57
V33 V57
V34 V57
V39 V57
V40 V57
V42 V57
V43 V57
V50 V57
V51 V57
V52 V57
V58 V57
V59 V57
V60 V57
V63 V57
V64 V57
V71 V57
V72 V57
V73 V57
V74 V57
V79 V57
V80 V57
V81 V57
V84 V57
V85 V57
V92 V57
V93 V57
V94 V57
V302 V57
V303 V57
V304 V57
card3 V58
addr2 V58
V15 V58
V16 V58
V17 V58
V21 V58
V22 V58
V31 V58
V32 V58
V33 V58
V34 V58
V39 V58
V40 V58
V42 V58
V43 V58
V50 V58
V51 V58
V52 V58
V57 V58
V59 V58
V60 V58
V63 V58
V64 V58
V71 V58
V72 V58
V73 V58
V74 V58
V79 V58
V80 V58
V81 V58
V84 V58
V85 V58
V92 V58
V93 V58
V94 V58
V302 V58
V303 V58
V304 V58
V15 V59
V17 V59
V18 V59
V21 V59
V22 V59
V31 V59
V33 V59
V39 V59
V40 V59
V42 V59
V43 V59
V50 V59
V51 V59
V52 V59
V57 V59
V58 V59
V60 V59
V63 V59
V64 V59
V71 V59
V72 V59
V73 V59
V74 V59
V79 V59
V80 V59
V81 V59
V84 V59
V85 V59
V92 V59
V93 V59
V94 V59
V302 V59
V303 V59
V304 V59
V15 V60
V17 V60
V18 V60
V21 V60
V22 V60
V31 V60
V33 V60
V39 V60
V40 V60
V42 V60
V43 V60
V50 V60
V51 V60
V52 V60
V57 V60
V58 V60
V59 V60
V63 V60
V64 V60
V71 V60
V72 V60
V73 V60
V74 V60
V79 V60
V80 V60
V81 V60
V84 V60
V85 V60
V92 V60
V93 V60
V94 V60
V302 V60
V303 V60
V304 V60
V19 V61
V62 V61
V82 V61
V61 V62
V15 V63
V17 V63
V18 V63
V21 V63
V22 V63
V31 V63
V33 V63
V39 V63
V40 V63
V42 V63
V43 V63
V50 V63
V51 V63
V52 V63
V57 V63
V58 V63
V59 V63
V60 V63
V64 V63
V71 V63
V72 V63
V73 V63
V74 V63
V79 V63
V80 V63
V81 V63
V84 V63
V85 V63
V92 V63
V93 V63
V94 V63
V302 V63
V303 V63
V304 V63
V15 V64
V17 V64
V18 V64
V21 V64
V22 V64
V31 V64
V33 V64
V39 V64
V40 V64
V42 V64
V43 V64
V50 V64
V51 V64
V52 V64
V57 V64
V58 V64
V59 V64
V60 V64
V63 V64
V71 V64
V72 V64
V73 V64
V74 V64
V79 V64
V80 V64
V81 V64
V84 V64
V85 V64
V92 V64
V93 V64
V94 V64
V302 V64
V303 V64
V304 V64
V14 V65
V41 V65
V88 V65
V67 V66
V66 V67
V27 V68
V28 V68
V89 V68
V10 V69
V11 V69
V29 V69
V30 V69
V48 V69
V49 V69
V70 V69
V90 V69
V91 V69
V10 V70
V11 V70
V29 V70
V30 V70
V48 V70
V49 V70
V69 V70
V90 V70
V91 V70
addr2 V71
V15 V71
V16 V71
V17 V71
V18 V71
V21 V71
V22 V71
V31 V71
V32 V71
V33 V71
V34 V71
V39 V71
V40 V71
V42 V71
V43 V71
V50 V71
V51 V71
V52 V71
V57 V71
V58 V71
V59 V71
V60 V71
V63 V71
V64 V71
V72 V71
V73 V71
V74 V71
V79 V71
V80 V71
V81 V71
V84 V71
V85 V71
V92 V71
V93 V71
V94 V71
V302 V71
V303 V71
V304 V71
addr2 V72
V15 V72
V16 V72
V17 V72
V18 V72
V21 V72
V22 V72
V31 V72
V32 V72
V33 V72
V34 V72
V39 V72
V40 V72
V42 V72
V43 V72
V50 V72
V51 V72
V52 V72
V57 V72
V58 V72
V59 V72
V60 V72
V63 V72
V64 V72
V71 V72
V73 V72
V74 V72
V79 V72
V80 V72
V81 V72
V84 V72
V85 V72
V92 V72
V93 V72
V94 V72
V302 V72
V303 V72
V304 V72
card3 V73
addr2 V73
V15 V73
V16 V73
V17 V73
V21 V73
V22 V73
V31 V73
V32 V73
V33 V73
V34 V73
V39 V73
V40 V73
V42 V73
V43 V73
V50 V73
V51 V73
V52 V73
V57 V73
V58 V73
V59 V73
V60 V73
V63 V73
V64 V73
V71 V73
V72 V73
V74 V73
V79 V73
V80 V73
V81 V73
V84 V73
V85 V73
V92 V73
V93 V73
V94 V73
V302 V73
V303 V73
V304 V73
card3 V74
addr2 V74
V15 V74
V16 V74
V21 V74
V22 V74
V31 V74
V32 V74
V33 V74
V34 V74
V39 V74
V40 V74
V42 V74
V43 V74
V50 V74
V51 V74
V52 V74
V57 V74
V58 V74
V59 V74
V60 V74
V63 V74
V64 V74
V71 V74
V72 V74
V73 V74
V79 V74
V80 V74
V81 V74
V84 V74
V85 V74
V92 V74
V93 V74
V94 V74
V302 V74
V303 V74
V304 V74
V12 V75
V35 V75
V36 V75
V76 V75
V13 V76
V35 V76
V36 V76
V75 V76
V78 V77
V38 V78
V77 V78
card3 V79
addr2 V79
V15 V79
V16 V79
V21 V79
V22 V79
V31 V79
V32 V79
V33 V79
V34 V79
V39 V79
V40 V79
V42 V79
V43 V79
V50 V79
V51 V79
V52 V79
V57 V79
V58 V79
V59 V79
V60 V79
V63 V79
V64 V79
V71 V79
V72 V79
V73 V79
V74 V79
V80 V79
V81 V79
V84 V79
V85 V79
V92 V79
V93 V79
V94 V79
V302 V79
V17 V80
V18 V80
V21 V80
V22 V80
V31 V80
V39 V80
V40 V80
V42 V80
V43 V80
V50 V80
V51 V80
V52 V80
V57 V80
V58 V80
V59 V80
V60 V80
V63 V80
V64 V80
V71 V80
V72 V80
V73 V80
V74 V80
V79 V80
V81 V80
V84 V80
V85 V80
V92 V80
V93 V80
V94 V80
V302 V80
V303 V80
V304 V80
V17 V81
V18 V81
V21 V81
V22 V81
V31 V81
V39 V81
V40 V81
V42 V81
V43 V81
V50 V81
V51 V81
V57 V81
V58 V81
V59 V81
V60 V81
V63 V81
V64 V81
V71 V81
V72 V81
V73 V81
V74 V81
V79 V81
V80 V81
V84 V81
V85 V81
V92 V81
V93 V81
V94 V81
V302 V81
V303 V81
V304 V81
V4 V82
V19 V82
V61 V82
V83 V82
V82 V83
V15 V84
V17 V84
V18 V84
V21 V84
V22 V84
V31 V84
V32 V84
V33 V84
V39 V84
V40 V84
V42 V84
V43 V84
V50 V84
V51 V84
V52 V84
V57 V84
V58 V84
V59 V84
V60 V84
V63 V84
V64 V84
V71 V84
V72 V84
V73 V84
V74 V84
V79 V84
V80 V84
V81 V84
V85 V84
V92 V84
V93 V84
V94 V84
V302 V84
V303 V84
V304 V84
V17 V85
V18 V85
V21 V85
V22 V85
V31 V85
V33 V85
V39 V85
V40 V85
V42 V85
V43 V85
V50 V85
V51 V85
V52 V85
V57 V85
V58 V85
V59 V85
V60 V85
V63 V85
V64 V85
V71 V85
V72 V85
V73 V85
V74 V85
V79 V85
V80 V85
V81 V85
V84 V85
V92 V85
V93 V85
V94 V85
V302 V85
V303 V85
V304 V85
V87 V86
V45 V87
V86 V87
V14 V88
V41 V88
V65 V88
V27 V89
V28 V89
V68 V89
V10 V90
V11 V90
V29 V90
V30 V90
V48 V90
V49 V90
V69 V90
V70 V90
V91 V90
V10 V91
V11 V91
V29 V91
V30 V91
V48 V91
V49 V91
V69 V91
V70 V91
V90 V91
V15 V92
V16 V92
V17 V92
V18 V92
V21 V92
V22 V92
V31 V92
V32 V92
V33 V92
V34 V92
V39 V92
V40 V92
V42 V92
V43 V92
V50 V92
V51 V92
V52 V92
V57 V92
V58 V92
V59 V92
V60 V92
V63 V92
V64 V92
V71 V92
V72 V92
V73 V92
V74 V92
V79 V92
V80 V92
V81 V92
V84 V92
V85 V92
V93 V92
V94 V92
V302 V92
V303 V92
V304 V92
V15 V93
V16 V93
V17 V93
V18 V93
V21 V93
V22 V93
V31 V93
V32 V93
V33 V93
V34 V93
V39 V93
V40 V93
V42 V93
V43 V93
V50 V93
V51 V93
V52 V93
V57 V93
V58 V93
V59 V93
V60 V93
V63 V93
V64 V93
V71 V93
V72 V93
V73 V93
V74 V93
V79 V93
V80 V93
V81 V93
V84 V93
V85 V93
V92 V93
V94 V93
V302 V93
V303 V93
V304 V93
card3 V94
addr2 V94
V15 V94
V16 V94
V17 V94
V21 V94
V22 V94
V31 V94
V32 V94
V33 V94
V34 V94
V39 V94
V40 V94
V42 V94
V43 V94
V50 V94
V51 V94
V52 V94
V57 V94
V58 V94
V59 V94
V60 V94
V63 V94
V64 V94
V71 V94
V72 V94
V73 V94
V74 V94
V79 V94
V80 V94
V81 V94
V84 V94
V85 V94
V92 V94
V93 V94
V302 V94
V304 V94
id_17 V94
V101 V95
V97 V96
V99 V96
V102 V96
V103 V96
V96 V97
V102 V97
V103 V97
V284 V98
V96 V99
V100 V99
V285 V99
V99 V100
V287 V100
V95 V101
V96 V102
V97 V102
V103 V102
V133 V102
V96 V103
V97 V103
V102 V103
V106 V104
V181 V104
V184 V104
V185 V104
V235 V104
V297 V104
V106 V105
V104 V106
V105 V106
V181 V106
V184 V106
V185 V106
V235 V106
V299 V106
V109 V108
V110 V108
V111 V108
V112 V108
V113 V108
V108 V109
V110 V109
V108 V110
V109 V110
V111 V110
V112 V110
V113 V110
V108 V111
V110 V111
V112 V111
V113 V111
V108 V112
V110 V112
V111 V112
V113 V112
V108 V113
V110 V113
V111 V113
V112 V113
V116 V114
V116 V115
V114 V116
V115 V116
V118 V117
V119 V117
V117 V118
V119 V118
V117 V119
V118 V119
V121 V120
V122 V120
V120 V121
V122 V121
V120 V122
V121 V122
V124 V123
V125 V123
V123 V124
V125 V124
V123 V125
V124 V125
V128 V126
V135 V126
V136 V126
V137 V126
V202 V126
V214 V126
V216 V126
V226 V126
V263 V126
V276 V126
V278 V126
V306 V126
V128 V127
V133 V127
V202 V127
V214 V127
V216 V127
V226 V127
V263 V127
V276 V127
V278 V127
V126 V128
V127 V128
V134 V128
V202 V128
V214 V128
V216 V128
V226 V128
V263 V128
V276 V128
V278 V128
V308 V128
V309 V129
V131 V130
V310 V130
V130 V131
V312 V131
V134 V132
V316 V132
V102 V133
V127 V133
V134 V133
V128 V134
V132 V134
V133 V134
V126 V135
V136 V135
V137 V135
V202 V135
V214 V135
V216 V135
V226 V135
V263 V135
V276 V135
V278 V135
V306 V135
V319 V135
V320 V135
V321 V135
V126 V136
V135 V136
V137 V136
V202 V136
V214 V136
V216 V136
V226 V136
V263 V136
V276 V136
V278 V136
V319 V136
V320 V136
V321 V136
V126 V137
V135 V137
V136 V137
V202 V137
V214 V137
V216 V137
V226 V137
V263 V137
V276 V137
V278 V137
V306 V137
V319 V137
V320 V137
V321 V137
V168 V167
V172 V167
V176 V167
V177 V167
V178 V167
V179 V167
V186 V167
V190 V167
V191 V167
V196 V167
V199 V167
V205 V167
V217 V167
V167 V168
V172 V168
V176 V168
V178 V168
V179 V168
V180 V168
V182 V168
V183 V168
V186 V168
V187 V168
V190 V168
V191 V168
V192 V168
V193 V168
V196 V168
V199 V168
V203 V168
V204 V168
V205 V168
V207 V168
V212 V168
V213 V168
V234 V168
V171 V170
V200 V170
V170 V171
V201 V171
V167 V172
V168 V172
V176 V172
V178 V172
V179 V172
V180 V172
V186 V172
V187 V172
V190 V172
V191 V172
V192 V172
V193 V172
V196 V172
V199 V172
V203 V172
V204 V172
V205 V172
V207 V172
V212 V172
V286 V173
V175 V174
V174 V175
V167 V176
V168 V176
V172 V176
V177 V176
V178 V176
V179 V176
V186 V176
V187 V176
V190 V176
V191 V176
V192 V176
V193 V176
V196 V176
V199 V176
V203 V176
V205 V176
V207 V176
V212 V176
V228 V176
V167 V177
V176 V177
V190 V177
V199 V177
V231 V177
V167 V178
V168 V178
V172 V178
V176 V178
V179 V178
V180 V178
V182 V178
V186 V178
V187 V178
V190 V178
V191 V178
V192 V178
V193 V178
V196 V178
V199 V178
V203 V178
V204 V178
V205 V178
V207 V178
V209 V178
V212 V178
V213 V178
V234 V178
V167 V179
V168 V179
V172 V179
V176 V179
V178 V179
V180 V179
V182 V179
V186 V179
V187 V179
V190 V179
V191 V179
V192 V179
V193 V179
V196 V179
V199 V179
V203 V179
V204 V179
V207 V179
V212 V179
V213 V179
V231 V179
V233 V179
V168 V180
V172 V180
V178 V180
V179 V180
V182 V180
V183 V180
V186 V180
V187 V180
V190 V180
V191 V180
V192 V180
V193 V180
V196 V180
V203 V180
V204 V180
V207 V180
V212 V180
V213 V180
V234 V180
V104 V181
V106 V181
V183 V181
V184 V181
V185 V181
V235 V181
V237 V181
V297 V181
V168 V182
V178 V182
V179 V182
V180 V182
V183 V182
V186 V182
V187 V182
V191 V182
V192 V182
V193 V182
V196 V182
V203 V182
V204 V182
V207 V182
V212 V182
V213 V182
V234 V182
V168 V183
V180 V183
V181 V183
V182 V183
V192 V183
V193 V183
V204 V183
V207 V183
V235 V183
V237 V183
V104 V184
V106 V184
V181 V184
V185 V184
V235 V184
V237 V184
V238 V184
V239 V184
V297 V184
V300 V184
V301 V184
V104 V185
V106 V185
V181 V185
V184 V185
V235 V185
V237 V185
V238 V185
V239 V185
V300 V185
V301 V185
V167 V186
V168 V186
V172 V186
V176 V186
V178 V186
V179 V186
V180 V186
V182 V186
V187 V186
V190 V186
V191 V186
V192 V186
V193 V186
V196 V186
V199 V186
V203 V186
V204 V186
V205 V186
V207 V186
V212 V186
V213 V186
V168 V187
V172 V187
V176 V187
V178 V187
V179 V187
V180 V187
V182 V187
V186 V187
V190 V187
V191 V187
V192 V187
V193 V187
V196 V187
V199 V187
V203 V187
V204 V187
V205 V187
V207 V187
V209 V187
V212 V187
V213 V187
V234 V187
V189 V188
V200 V188
V201 V188
V188 V189
V200 V189
V201 V189
V167 V190
V168 V190
V172 V190
V176 V190
V177 V190
V178 V190
V179 V190
V180 V190
V186 V190
V187 V190
V191 V190
V192 V190
V193 V190
V196 V190
V199 V190
V203 V190
V204 V190
V205 V190
V207 V190
V212 V190
V213 V190
V167 V191
V168 V191
V172 V191
V176 V191
V178 V191
V179 V191
V180 V191
V182 V191
V186 V191
V187 V191
V190 V191
V192 V191
V193 V191
V196 V191
V199 V191
V203 V191
V204 V191
V205 V191
V207 V191
V212 V191
V213 V191
V234 V191
V168 V192
V172 V192
V176 V192
V178 V192
V179 V192
V180 V192
V182 V192
V183 V192
V186 V192
V187 V192
V190 V192
V191 V192
V193 V192
V196 V192
V199 V192
V203 V192
V204 V192
V205 V192
V207 V192
V209 V192
V212 V192
V213 V192
V234 V192
V168 V193
V172 V193
V176 V193
V178 V193
V179 V193
V180 V193
V182 V193
V183 V193
V186 V193
V187 V193
V190 V193
V191 V193
V192 V193
V196 V193
V199 V193
V203 V193
V204 V193
V205 V193
V207 V193
V212 V193
V213 V193
V234 V193
V195 V194
V197 V194
V198 V194
V194 V195
V197 V195
V198 V195
V167 V196
V168 V196
V172 V196
V176 V196
V178 V196
V179 V196
V180 V196
V182 V196
V186 V196
V187 V196
V190 V196
V191 V196
V192 V196
V193 V196
V199 V196
V203 V196
V204 V196
V205 V196
V207 V196
V212 V196
V213 V196
V234 V196
V194 V197
V195 V197
V198 V197
V194 V198
V195 V198
V197 V198
V167 V199
V168 V199
V172 V199
V176 V199
V177 V199
V178 V199
V179 V199
V186 V199
V187 V199
V190 V199
V191 V199
V192 V199
V193 V199
V196 V199
V203 V199
V205 V199
V207 V199
V212 V199
V170 V200
V188 V200
V189 V200
V201 V200
V171 V201
V188 V201
V189 V201
V200 V201
V126 V202
V127 V202
V128 V202
V135 V202
V136 V202
V137 V202
V214 V202
V215 V202
V216 V202
V226 V202
V263 V202
V265 V202
V276 V202
V277 V202
V278 V202
V306 V202
V308 V202
V319 V202
V320 V202
V321 V202
V168 V203
V172 V203
V176 V203
V178 V203
V179 V203
V180 V203
V182 V203
V186 V203
V187 V203
V190 V203
V191 V203
V192 V203
V193 V203
V196 V203
V199 V203
V204 V203
V205 V203
V207 V203
V209 V203
V212 V203
V213 V203
V215 V203
V226 V203
V234 V203
V263 V203
V276 V203
V277 V203
V278 V203
V168 V204
V172 V204
V178 V204
V179 V204
V180 V204
V182 V204
V183 V204
V186 V204
V187 V204
V190 V204
V191 V204
V192 V204
V193 V204
V196 V204
V203 V204
V205 V204
V207 V204
V212 V204
V213 V204
V215 V204
V226 V204
V263 V204
V265 V204
V276 V204
V277 V204
V278 V204
V167 V205
V168 V205
V172 V205
V176 V205
V178 V205
V186 V205
V187 V205
V190 V205
V191 V205
V192 V205
V193 V205
V196 V205
V199 V205
V203 V205
V204 V205
V207 V205
V212 V205
V266 V205
V269 V205
V311 V206
V168 V207
V172 V207
V176 V207
V178 V207
V179 V207
V180 V207
V182 V207
V183 V207
V186 V207
V187 V207
V190 V207
V191 V207
V192 V207
V193 V207
V196 V207
V199 V207
V203 V207
V204 V207
V205 V207
V212 V207
V213 V207
V234 V207
V210 V208
V178 V209
V187 V209
V192 V209
V203 V209
V212 V209
V208 V210
V271 V210
V272 V210
V273 V211
V168 V212
V172 V212
V176 V212
V178 V212
V179 V212
V180 V212
V182 V212
V186 V212
V187 V212
V190 V212
V191 V212
V192 V212
V193 V212
V196 V212
V199 V212
V203 V212
V204 V212
V205 V212
V207 V212
V209 V212
V213 V212
V234 V212
V168 V213
V178 V213
V179 V213
V180 V213
V182 V213
V186 V213
V187 V213
V190 V213
V191 V213
V192 V213
V193 V213
V196 V213
V203 V213
V204 V213
V207 V213
V212 V213
V273 V213
V126 V214
V127 V214
V128 V214
V135 V214
V136 V214
V137 V214
V202 V214
V215 V214
V216 V214
V226 V214
V263 V214
V265 V214
V276 V214
V277 V214
V278 V214
V306 V214
V308 V214
V319 V214
V320 V214
V321 V214
V202 V215
V203 V215
V204 V215
V214 V215
V216 V215
V226 V215
V263 V215
V265 V215
V276 V215
V277 V215
V278 V215
V306 V215
V319 V215
V320 V215
V321 V215
V126 V216
V127 V216
V128 V216
V135 V216
V136 V216
V137 V216
V202 V216
V214 V216
V215 V216
V226 V216
V263 V216
V265 V216
V276 V216
V277 V216
V278 V216
V306 V216
V308 V216
V319 V216
V320 V216
V321 V216
V167 V217
V228 V217
V231 V217
V233 V217
V246 V217
V257 V217

In [52]:
df.drop(columns=['V317','V318','V319','V320','id_17'], inplace=True)

In [53]:
df.columns

Index(['isFraud', 'TransactionDT', 'TransactionAmt', 'ProductCD', 'card1',
       'card2', 'card3', 'card4', 'card5', 'card6',
       ...
       'id_20', 'id_28', 'id_29', 'id_31', 'id_35', 'id_36', 'id_37', 'id_38',
       'DeviceType', 'DeviceInfo'],
      dtype='object', length=347)

In [54]:
df.filter(like='id_').dtypes

id_01    float64
id_02    float64
id_05    float64
id_06    float64
id_11    float64
id_12     object
id_15     object
id_16     object
id_19    float64
id_20    float64
id_28     object
id_29     object
id_31     object
id_35     object
id_36     object
id_37     object
id_38     object
dtype: object

Highly correlated features contain very similar information. When two features are strongly correlated, they can introduce redundancy in the model.

To handle this, we:

Calculate the correlation matrix for numerical features.

Identify feature pairs with correlation greater than a selected threshold (e.g., 0.7).

Remove one feature from each highly correlated pair.

This step helps:

 1. Reduce multicollinearity

 2.  Simplify the model

3.   Improve model generalization

After removing unpredictive and highly correlated features, the dataset becomes cleaner and more suitable for model training.

In [ ]:
## step 4-  fill Missing values

In [55]:
num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [56]:
cat_cols = df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].fillna("Unknown")

In [57]:
df.isnull().sum().sum()

np.int64(0)

In [59]:
df.head(3)

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,0,86400,68.5,W,13926,375.0,150.0,discover,142.0,credit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

### Filling Missing Values

The dataset contains missing values in both numerical and categorical features.
To prepare the data for machine learning models, these missing values need to be handled.

* **Numerical Features:** Missing values are filled using the **median** of the column.
* **Categorical Features:** Missing values are replaced with a new category called **"Unknown"**.

This ensures that the dataset has no missing values and is ready for further preprocessing and model training.

In [61]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [62]:
df.to_csv('/content/drive/MyDrive/cleaned_fraud_data.csv', index=False)